import threading
from blazefl.core.utils import process_tensors_in_object as process_tensors_in_object, reconstruct_from_shared_memory as reconstruct_from_shared_memory
from collections.abc import Iterable
from concurrent.futures import Future as Future
from multiprocessing.pool import ApplyResult as ApplyResult
from typing import Protocol, TypeVar

UplinkPackage = TypeVar('UplinkPackage')
DownlinkPackage = TypeVar('DownlinkPackage', contravariant=True)

class BaseClientTrainer(Protocol[UplinkPackage, DownlinkPackage]):
    def uplink_package(self) -> list[UplinkPackage]: ...
    def local_process(self, payload: DownlinkPackage, cid_list: list[int]) -> None: ...
ClientConfig = TypeVar('ClientConfig')
BufferPackage = TypeVar('BufferPackage')

class ProcessPoolClientTrainer(BaseClientTrainer[UplinkPackage, DownlinkPackage], Protocol[UplinkPackage, DownlinkPackage, ClientConfig, BufferPackage]):
    num_parallels: int
    device: str
    device_count: int
    cache: list[UplinkPackage]
    stop_event: threading.Event
    def progress_fn(self, it: list[ApplyResult]) -> Iterable[ApplyResult]: ...
    def get_client_config(self, cid: int) -> ClientConfig: ...
    def get_client_device(self, cid: int) -> str: ...
    @staticmethod
    def worker(config: ClientConfig, payload: DownlinkPackage, device: str, stop_event: threading.Event, *, shm_buffer: BufferPackage | None = None) -> BufferPackage: ...
    def prepare_uplink_package_buffer(self) -> BufferPackage: ...
    def convert_buffer_to_uplink(self, buffer: BufferPackage) -> UplinkPackage: ...
    def shutdown(self) -> None: ...
    def __del__(self) -> None: ...
    def local_process(self, payload: DownlinkPackage, cid_list: list[int]) -> None: ...

class ThreadPoolClientTrainer(BaseClientTrainer[UplinkPackage, DownlinkPackage], Protocol[UplinkPackage, DownlinkPackage]):
    num_parallels: int
    device: str
    device_count: int
    cache: list[UplinkPackage]
    stop_event: threading.Event
    def progress_fn(self, it: list[Future[UplinkPackage]]) -> Iterable[Future[UplinkPackage]]: ...
    def worker(self, cid: int, device: str, payload: DownlinkPackage, stop_event: threading.Event) -> UplinkPackage: ...
    def get_client_device(self, cid: int) -> str: ...
    def local_process(self, payload: DownlinkPackage, cid_list: list[int]) -> None: ...
