import torch
from dataclasses import dataclass
from typing import Literal

@dataclass(frozen=True)
class SHMHandle: ...

def process_tensors_in_object[T](obj: T, mode: Literal['move', 'replace'], max_depth: int = 10) -> T: ...
def reconstruct_from_shared_memory[T](handle_obj: T, shm_obj: T) -> T: ...
def serialize_model(model: torch.nn.Module, cpu: bool = True) -> torch.Tensor: ...
def deserialize_model(model: torch.nn.Module, serialized_parameters: torch.Tensor) -> None: ...
